name: ges_absence
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6  
  http: ^1.1.0
  shared_preferences: ^2.2.1
  intl: ^0.18.1
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  image_picker: ^1.1.2
  http_parser: ^4.0.2
  path: ^1.8.3
  path_provider: ^2.1.1
  qr_flutter: ^4.0.0
  table_calendar: ^3.0.9
  mobile_scanner: ^3.5.4
  cloudinary_public: ^0.21.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ism_logo.png
